#!/bin/bash
#
# OpenEMS Modem 4G Sudoers Setup Script
# 
# This script configures passwordless sudo access for PPP modem commands
# Required for io.openems.edge.modem.4g bundle to modify quectel-pppd.sh
#
# Usage: sudo ./setup-modem-sudoers.sh [username]
#        Default username: openems
#

set -e

# Default username
OPENEMS_USER="${1:-openems}"
SUDOERS_FILE="/etc/sudoers.d/openems-modem"
SCRIPT_PATH="/etc/ppp/quectel-pppd.sh"

echo "=============================================="
echo "OpenEMS Modem 4G Sudoers Setup"
echo "=============================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)"
    exit 1
fi

# Check if user exists
if ! id "$OPENEMS_USER" &>/dev/null; then
    echo "WARNING: User '$OPENEMS_USER' does not exist."
    echo "         Creating user..."
    useradd -r -s /bin/false "$OPENEMS_USER" 2>/dev/null || true
fi

echo "Configuring sudo access for user: $OPENEMS_USER"
echo ""

# Create sudoers file
cat > "$SUDOERS_FILE" << EOF
# OpenEMS Modem 4G Management
# Allows passwordless access to PPP modem configuration commands
# Generated by setup-modem-sudoers.sh

# sed - for editing quectel-pppd.sh config file
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/bin/sed
$OPENEMS_USER ALL=(ALL) NOPASSWD: /bin/sed

# killall - for stopping pppd process
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/bin/killall
$OPENEMS_USER ALL=(ALL) NOPASSWD: /bin/killall

# pppd - for PPP connection
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/sbin/pppd
$OPENEMS_USER ALL=(ALL) NOPASSWD: /sbin/pppd

# quectel-pppd.sh script - for starting 4G connection
$OPENEMS_USER ALL=(ALL) NOPASSWD: $SCRIPT_PATH

# mmcli - for modem status monitoring (optional)
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/bin/mmcli

# cat - for reading config file
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/bin/cat
$OPENEMS_USER ALL=(ALL) NOPASSWD: /bin/cat

# grep - for parsing config
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/bin/grep
$OPENEMS_USER ALL=(ALL) NOPASSWD: /bin/grep
EOF

# Set correct permissions
chmod 440 "$SUDOERS_FILE"

# Validate sudoers syntax
if visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
    echo "✓ Sudoers file created: $SUDOERS_FILE"
    echo ""
    echo "Granted permissions:"
    echo "  - sed (for editing APN config)"
    echo "  - killall (for stopping pppd)"
    echo "  - pppd (for PPP connection)"
    echo "  - $SCRIPT_PATH (PPP script)"
    echo "  - mmcli (modem status - optional)"
    echo "  - cat, grep (for reading config)"
    echo ""
else
    echo "ERROR: Invalid sudoers syntax. Removing file..."
    rm -f "$SUDOERS_FILE"
    exit 1
fi

# Check if quectel-pppd.sh exists
if [ -f "$SCRIPT_PATH" ]; then
    echo "✓ Found $SCRIPT_PATH"
    # Make sure it's executable
    chmod +x "$SCRIPT_PATH"
else
    echo "! WARNING: $SCRIPT_PATH not found."
    echo "  Please ensure the Quectel PPP script is installed."
fi

echo ""
echo "=============================================="
echo "Setup Complete!"
echo "=============================================="
echo ""
echo "The following commands can now be run by '$OPENEMS_USER' without password:"
echo "  - sudo sed -i '...' $SCRIPT_PATH"
echo "  - sudo killall pppd"  
echo "  - sudo $SCRIPT_PATH"
echo "  - sudo mmcli ..."
echo ""
echo "OpenEMS can now configure 4G modem without running as root."
echo ""
echo "To remove these permissions, delete: $SUDOERS_FILE"
echo ""
