#!/bin/bash
#
# OpenEMS Network & Modem Sudoers Setup Script
# 
# This script configures passwordless sudo access for nmcli and mmcli commands
# Required for io.openems.edge.network.manager and io.openems.edge.modem.4g bundles
#
# Usage: sudo ./setup-network-sudoers.sh [username]
#        Default username: openems
#

set -e

# Default username
OPENEMS_USER="${1:-openems}"
SUDOERS_FILE="/etc/sudoers.d/openems-network"

echo "=============================================="
echo "OpenEMS Network & Modem Sudoers Setup"
echo "=============================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)"
    exit 1
fi

# Check if user exists
if ! id "$OPENEMS_USER" &>/dev/null; then
    echo "WARNING: User '$OPENEMS_USER' does not exist."
    echo "         Creating user..."
    useradd -r -s /bin/false "$OPENEMS_USER" 2>/dev/null || true
fi

echo "Configuring sudo access for user: $OPENEMS_USER"
echo ""

# Create sudoers file
cat > "$SUDOERS_FILE" << EOF
# OpenEMS Network & Modem Management
# Allows passwordless access to network configuration commands
# Generated by setup-network-sudoers.sh

# NetworkManager (nmcli) - for network configuration
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/bin/nmcli

# ModemManager (mmcli) - for 4G modem management  
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/bin/mmcli

# IP command - for network interface management
$OPENEMS_USER ALL=(ALL) NOPASSWD: /sbin/ip
$OPENEMS_USER ALL=(ALL) NOPASSWD: /usr/sbin/ip
EOF

# Set correct permissions
chmod 440 "$SUDOERS_FILE"

# Validate sudoers syntax
if visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
    echo "✓ Sudoers file created: $SUDOERS_FILE"
    echo ""
    echo "Granted permissions:"
    echo "  - nmcli (NetworkManager CLI)"
    echo "  - mmcli (ModemManager CLI)" 
    echo "  - ip (Network interface management)"
    echo ""
else
    echo "ERROR: Invalid sudoers syntax. Removing file..."
    rm -f "$SUDOERS_FILE"
    exit 1
fi

# Verify
echo "Verifying configuration..."
if sudo -u "$OPENEMS_USER" sudo -n nmcli general status &>/dev/null 2>&1; then
    echo "✓ nmcli access verified"
else
    echo "! nmcli verification skipped (user may not have shell access)"
fi

echo ""
echo "=============================================="
echo "Setup Complete!"
echo "=============================================="
echo ""
echo "The following commands can now be run by '$OPENEMS_USER' without password:"
echo "  - sudo nmcli ..."
echo "  - sudo mmcli ..."
echo "  - sudo ip ..."
echo ""
echo "To remove these permissions, delete: $SUDOERS_FILE"
echo ""
